(defn emit-string (var str)
  (let ((len (string-length str))
        (tmp (generate-var)))
    (emit (format "  ~A = call i64 @internal_heap-current-pointer()" tmp))
    (begin
      (defn helper (str idx len)
         (if (< idx len)
           (let* ((char (string-ref str idx))
                  (ord (char->integer char)))
             (emit (format "  call i64 @internal_heap-store-byte(i8 ~A)" ord))
             (helper str (add1 idx) len))
           (emit (format "  call i64 @internal_heap-store-byte(i8 0)"))))
      (helper str 0 len))
    (emit (format "  call void @internal_heap-align-index()"))
    (emit (format  "~A = or i64 ~A, 5" var tmp))))
