(defn error (msg val)
      (print "ERROR: ")
      (print msg)
      (print " ")
      (inspect val))

(def cur-char #f)
(defn read-char ()
      (if (char? cur-char)
        (let ((old cur-char))
          (set! cur-char #f)
          old)
        (getchar)))
(defn peek-char ()
      (if (char? cur-char)
        cur-char
        (let ((new (getchar)))
          (set! cur-char new)
          new)))

(inspect cur-char)
